import {
  isObject,
  onArrayValue,
  overField,
  sortKeys,
  uniqAndSortStrings,
  uniqStrings,
  type FieldSorter,
} from "../core/primitives.ts";
import { sortDependencies, sortWorkspaces } from "./dependencies.ts";
import { sortExports } from "./exports.ts";
import {
  alphabetical,
  bySubOrder,
  GIT_HOOKS,
  PERSON_ORDER,
  sortPersonList,
  TYPE_URL_ORDER,
} from "./helpers.ts";
import { sortEslintConfig, sortPrettierConfig } from "./lint-format.ts";
import { sortScripts } from "./scripts.ts";
import { sortPnpm, sortWireit } from "./tools.ts";

export const defaultFieldSorters: Record<string, FieldSorter> = {
  categories: uniqStrings,
  keywords: uniqStrings,
  bugs: bySubOrder(["url", "email"]),
  repository: bySubOrder(TYPE_URL_ORDER),
  funding: bySubOrder(TYPE_URL_ORDER),
  license: bySubOrder(TYPE_URL_ORDER),
  author: bySubOrder(PERSON_ORDER),
  maintainers: sortPersonList,
  contributors: sortPersonList,
  exports: sortExports,
  bin: alphabetical,
  directories: bySubOrder(["lib", "bin", "man", "doc", "example", "test"]),
  files: uniqStrings,
  workspaces: sortWorkspaces,
  binary: bySubOrder(["module_name", "module_path", "remote_path", "package_name", "host"]),
  scripts: sortScripts,
  betterScripts: sortScripts,
  wireit: sortWireit,
  contributes: alphabetical,
  activationEvents: uniqStrings,
  husky: (value, root) =>
    isObject(value) ? overField("hooks", bySubOrder(GIT_HOOKS))(value, root) : value,
  "simple-git-hooks": bySubOrder(GIT_HOOKS),
  commitlint: alphabetical,
  config: alphabetical,
  nodemonConfig: alphabetical,
  browserify: alphabetical,
  babel: alphabetical,
  xo: alphabetical,
  prettier: sortPrettierConfig,
  eslintConfig: sortEslintConfig,
  npmpkgjsonlint: alphabetical,
  npmPackageJsonLintConfig: alphabetical,
  npmpackagejsonlint: alphabetical,
  release: alphabetical,
  remarkConfig: alphabetical,
  ava: alphabetical,
  jest: alphabetical,
  "jest-junit": alphabetical,
  "jest-stare": alphabetical,
  mocha: alphabetical,
  nyc: alphabetical,
  c8: alphabetical,
  tap: alphabetical,
  oclif: bySubOrder([], true),
  resolutions: alphabetical,
  overrides: sortDependencies,
  dependencies: sortDependencies,
  devDependencies: sortDependencies,
  dependenciesMeta: bySubOrder([], true),
  peerDependencies: sortDependencies,
  peerDependenciesMeta: bySubOrder([], true),
  optionalDependencies: sortDependencies,
  bundledDependencies: uniqAndSortStrings,
  bundleDependencies: uniqAndSortStrings,
  extensionPack: uniqAndSortStrings,
  extensionDependencies: uniqAndSortStrings,
  engines: alphabetical,
  engineStrict: alphabetical,
  devEngines: (value, root) =>
    isObject(value)
      ? overField("packageManager", bySubOrder(["name", "version", "onFail"]))(value, root)
      : value,
  volta: bySubOrder(["node", "npm", "yarn"]),
  preferGlobal: alphabetical,
  publishConfig: alphabetical,
  badges: onArrayValue((items) =>
    items.map((item) => (isObject(item) ? sortKeys(item, ["description", "url", "href"]) : item)),
  ),
  galleryBanner: alphabetical,
  pnpm: sortPnpm,
};
